### ISSUE TITLE
Fatal error after app loaded with this plugin

### ISSUE THREAD

**Issue by trinitiwowka** [Linknpay/capacitor-facebook-events#1] opened 2024-01-08 19:39 UTC
```
01-08 16:37:49.694 25500 25500 D AndroidRuntime: Shutting down VM
01-08 16:37:49.697 25500 25500 E AndroidRuntime: FATAL EXCEPTION: main
01-08 16:37:49.697 25500 25500 E AndroidRuntime: Process: xxxx.yyyy.zzzzz PID: 25500
01-08 16:37:49.697 25500 25500 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{xxxx.yyyy.zzzzz/xxxx.yyyy.zzzzz.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context com.getcapacitor.Bridge.getContext()' on a null object reference
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context com.getcapacitor.Bridge.getContext()' on a null object reference
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.getcapacitor.Plugin.getContext(Plugin.java:201)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.dabchy.plugins.facebookevents.FacebookEvents.<init>(FacebookEvents.java:14)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.dabchy.plugins.facebookevents.FacebookEventsPlugin.<init>(FacebookEventsPlugin.java:12)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.getcapacitor.PluginHandle.load(PluginHandle.java:104)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.getcapacitor.Bridge.registerPlugin(Bridge.java:644)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:600)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.getcapacitor.Bridge.<init>(Bridge.java:215)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.getcapacitor.Bridge.<init>(Unknown Source:0)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.getcapacitor.Bridge$Builder.create(Bridge.java:1519)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:42)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:36)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8591)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8570)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
01-08 16:37:49.697 25500 25500 E AndroidRuntime: 	... 12 more
```

**Comment by Linknpay** [comment] 2024-01-15 17:22
Hi @trinitiwowka 

Thank you for bringing this issue to our attention. To better understand and resolve the problem, could you please provide additional information?

1. Detailed Description: Can you describe in more detail what actions lead to this error? Knowing the exact steps that trigger the issue can be very helpful.
2. Environment Details:
Android Version: Which version of Android is the device running?
Device Information: What is the make and model of the device?
Capacitor Version: Which version of Capacitor are you using?
Plugin Version: What is the version of the plugin you are using?
3. Code Snippets: If possible, could you share the relevant parts of your code where the plugin is initialized and used? This will help in identifying if there's a specific code block causing the issue.
4. Logs: Are there any other logs or error messages that appear before or after this exception? Sometimes preceding logs can provide clues about the root cause.
5. Framework Versions: Can you provide the versions of any other frameworks or libraries you are using in your project?
The more details you can provide, the better we can assist in diagnosing and resolving the issue.

Looking forward to your response.

Best regards,

**Comment by Linknpay** [comment] 2024-01-19 15:42
Hi @trinitiwowka we identified the issue with android and it will be resolved soon. Thank you.

**Closed** 2024-01-25 12:46 UTC
